{
 "title": "PostgreSQL Monitoring",
 "description": "PostgreSQL monitoring dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Database Size",
   "type": "stat",
   "description": "Current database size in MB",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_database_size_mb", "legendFormat": "DB Size" }
   ]
  },
  {
   "title": "Database Connections",
   "type": "timeseries",
   "description": "Current number of connections by state",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_activity_active_connections",
     "legendFormat": "Active"
    },
    {
     "expr": "pg_stat_activity_idle_connections",
     "legendFormat": "Idle"
    },
    {
     "expr": "pg_stat_activity_idle_in_transaction_connections",
     "legendFormat": "Idle in Transaction"
    }
   ]
  },
  {
   "title": "Database Operations",
   "type": "timeseries",
   "description": "Database operations per second",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "rate(pg_stat_user_tables_tuples_inserted[1m])",
     "legendFormat": "Inserts"
    },
    {
     "expr": "rate(pg_stat_user_tables_tuples_updated[1m])",
     "legendFormat": "Updates"
    },
    {
     "expr": "rate(pg_stat_user_tables_tuples_deleted[1m])",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "timeseries",
   "description": "Slow queries execution time",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(5, pg_stat_statements_mean_time_ms)",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "stat",
   "description": "Cache hit ratio",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_user_tables_shared_blocks_hit[5m])) / (sum(rate(pg_stat_user_tables_shared_blocks_hit[5m])) + sum(rate(pg_stat_user_tables_shared_blocks_read[5m])))",
     "legendFormat": "Cache Hit Ratio"
    }
   ]
  },
  {
   "title": "PostgreSQL Logs",
   "type": "logs",
   "description": "PostgreSQL logs",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"postgres\"}"
    }
   ]
  }
 ]
}